name: Misc
description: Template for things which are neither a bug report, feature request
title: "ADD A MEANINGFUL TITLE"
body:
- type: textarea
  id: description
  attributes:
    label: Description
    value: |
      Please don't use this template for bug reports or feature requests.
